/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 10:33:22 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-3763), 16.0, (-3763));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-3521.82576), 10.0, 0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 0.0, 3);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1), 430, 430);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-0.0085), (-1), (-1));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-0.0085), 11.58213476, (-1));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Example example0 = new Example();
      example0.test(430, 11.58213476, 430);
  }
}
