/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 08 14:30:50 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.0), 16.0, (-1835));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.0), 10.0, 0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, (-1286.8418326), (-833));
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1324.0), 1565, 1565);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.37604858E-4), (-26), (-26));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.37604858E-4), 10.6, (-26));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.6, (-26), (-26));
  }
}
