/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 08 14:36:34 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 12.0458002218614, 0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Example example0 = new Example();
      example0.test(20.0, 15.593819659195075, (-1686));
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Example example0 = new Example();
      example0.test(5.0, 15.465610342253115, 0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.0), 16.0, 0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 10.0, 0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1372.718657), (-1372.718657), 0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 12.0458002218614, 1);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.458498315654005, 10.458498315654005, (-2243));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Example example0 = new Example();
      example0.test(585.8367182357356, 10.458498315654005, (-2243));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-2243), 10.458498315654005, (-2243));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Example example0 = new Example();
      example0.test(872.5, 5278.0, (-1));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-343.6824283618614), (-343.6824283618614), (-1));
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 13.3431109, 3);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Example example0 = new Example();
      example0.test(13.3431109, 10.0, 3);
  }
}
