/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 03 10:36:47 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Example example0 = new Example();
      example0.test(19.0, 14.5191001066, (-2068));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Example example0 = new Example();
      example0.test(9.135256312940038, 14.5191001066, 3);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Example example0 = new Example();
      example0.test(20.0, 14.5191001066, (-2495));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Example example0 = new Example();
      example0.test(5.0, 14.5191001065984, 3);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Example example0 = new Example();
      example0.test(16.0, 16.0, (-1));
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-3904.61722), 10.0, 34);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.0), (-1.0), 0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Example example0 = new Example();
      example0.test(8.520870552046368, 14.5191001066, 1);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Example example0 = new Example();
      example0.test(8.520870552046368, 14.5191001066, 5);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Example example0 = new Example();
      example0.test(49.3, 14.5191001066, (-2071));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 14.5191001066, (-2071));
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Example example0 = new Example();
      example0.test(8.520870552046368, 14.5191001066, 0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-894.995), 0.0, 0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Example example0 = new Example();
      example0.test(1.0, 2031, (-1771));
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Example example0 = new Example();
      example0.test(1.0, 0, 0);
  }
}
